# Generated by Django 6.0.1 on 2026-01-15 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the barbershop/salon', max_length=255, verbose_name='Salon Name')),
                ('address', models.CharField(help_text='Full address of the salon', max_length=500, verbose_name='Address')),
                ('salon_code', models.CharField(editable=False, help_text='Unique code for the salon', max_length=100, unique=True, verbose_name='Salon Code')),
                ('phone', models.CharField(blank=True, help_text='Salon contact phone number', max_length=20, null=True, verbose_name='Contact Phone')),
                ('description', models.TextField(blank=True, help_text='Description about the salon', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Is salon currently active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Admin who owns this salon', limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_salons', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, help_text="Master's specialization (e.g., Hair stylist, Beard specialist)", max_length=255, null=True, verbose_name='Specialization')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='How many years of experience', verbose_name='Years of Experience')),
                ('bio', models.TextField(blank=True, help_text='Short bio about the master', null=True, verbose_name='Biography')),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status', verbose_name='Is Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('salon', models.ForeignKey(help_text='Salon where master works', on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='main.salon', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'Master',
                'verbose_name_plural': 'Masters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service (e.g., Haircut, Shave)', max_length=255, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, help_text='Service description', null=True, verbose_name='Description')),
                ('price', models.FloatField(help_text='Service price in KZT', verbose_name='Price')),
                ('duration', models.DurationField(help_text='Service duration (e.g., 30 minutes, 1 hour)', verbose_name='Duration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.salon', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['salon', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Booking Code')),
                ('appointment_date', models.DateField(help_text='Date of appointment', verbose_name='Appointment Date')),
                ('appointment_time', models.TimeField(help_text='Time of appointment', verbose_name='Appointment Time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('total_price', models.FloatField(default=0.0, help_text='Total price of all services', verbose_name='Total Price')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.PROTECT, related_name='master_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Master')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.salon', verbose_name='Salon')),
                ('services', models.ManyToManyField(help_text='Selected services for this booking', related_name='bookings', to='main.service', verbose_name='Services')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Weekday')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('is_working', models.BooleanField(default=True, help_text='Is master working on this day', verbose_name='Is Working')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Master')),
            ],
            options={
                'verbose_name': 'Work Schedule',
                'verbose_name_plural': 'Work Schedules',
                'ordering': ['master', 'weekday'],
            },
        ),
        migrations.AddIndex(
            model_name='salon',
            index=models.Index(fields=['salon_code'], name='main_salon_salon_c_904b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='salon',
            index=models.Index(fields=['owner', 'is_active'], name='main_salon_owner_i_3892b6_idx'),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['salon', 'is_approved'], name='main_master_salon_i_7854b6_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['salon', 'is_active'], name='main_servic_salon_i_25e10c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status'], name='main_bookin_client__2b7a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['master', 'appointment_date'], name='main_bookin_master__be9429_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['salon', 'appointment_date', 'status'], name='main_bookin_salon_i_0d3218_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('master', 'weekday')},
        ),
    ]
