# Generated by Django 6.0.2 on 2026-02-26 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterJobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Specialization')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('bio', models.TextField(blank=True, help_text='Шағын биография немесе жұмыс орнына хат', null=True, verbose_name='Bio / Cover Letter')),
                ('offered_services', models.TextField(blank=True, help_text='Comma-separated service names (e.g., Haircut, Beard Trim, Coloring)', null=True, verbose_name='Services Can Provide')),
                ('expected_salary', models.FloatField(blank=True, null=True, verbose_name='Expected Monthly Salary (KZT)')),
                ('answers', models.JSONField(blank=True, default=dict, help_text="Salon-specific questions and master's answers", verbose_name='Salon Q&A Answers')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL, verbose_name='Master')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='main.salon', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'Job Request',
                'verbose_name_plural': 'Job Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['salon', 'status'], name='main_master_salon_i_1c86cd_idx'), models.Index(fields=['master', 'status'], name='main_master_master__829152_idx')],
                'unique_together': {('master', 'salon')},
            },
        ),
    ]
