# Generated by Django 6.0.1 on 2026-01-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], default='client', help_text='User role', max_length=20, verbose_name='Role'),
        ),
    ]
